# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/wangzhao/code/cuckoo_hash

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/wangzhao/code/cuckoo_hash

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wangzhao/code/cuckoo_hash/CMakeFiles /home/wangzhao/code/cuckoo_hash/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wangzhao/code/cuckoo_hash/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cityhash

# Build rule for target.
cityhash: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cityhash
.PHONY : cityhash

# fast build rule for target.
cityhash/fast:
	$(MAKE) -f CMakeFiles/cityhash.dir/build.make CMakeFiles/cityhash.dir/build
.PHONY : cityhash/fast

#=============================================================================
# Target rules for targets named cuckoo_filter

# Build rule for target.
cuckoo_filter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cuckoo_filter
.PHONY : cuckoo_filter

# fast build rule for target.
cuckoo_filter/fast:
	$(MAKE) -f src/CMakeFiles/cuckoo_filter.dir/build.make src/CMakeFiles/cuckoo_filter.dir/build
.PHONY : cuckoo_filter/fast

cityhash/src/city.o: cityhash/src/city.cc.o

.PHONY : cityhash/src/city.o

# target to build an object file
cityhash/src/city.cc.o:
	$(MAKE) -f CMakeFiles/cityhash.dir/build.make CMakeFiles/cityhash.dir/cityhash/src/city.cc.o
.PHONY : cityhash/src/city.cc.o

cityhash/src/city.i: cityhash/src/city.cc.i

.PHONY : cityhash/src/city.i

# target to preprocess a source file
cityhash/src/city.cc.i:
	$(MAKE) -f CMakeFiles/cityhash.dir/build.make CMakeFiles/cityhash.dir/cityhash/src/city.cc.i
.PHONY : cityhash/src/city.cc.i

cityhash/src/city.s: cityhash/src/city.cc.s

.PHONY : cityhash/src/city.s

# target to generate assembly for a file
cityhash/src/city.cc.s:
	$(MAKE) -f CMakeFiles/cityhash.dir/build.make CMakeFiles/cityhash.dir/cityhash/src/city.cc.s
.PHONY : cityhash/src/city.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... cityhash"
	@echo "... edit_cache"
	@echo "... cuckoo_filter"
	@echo "... cityhash/src/city.o"
	@echo "... cityhash/src/city.i"
	@echo "... cityhash/src/city.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

